name: CI
on: [push, pull_request]
jobs:
    linux-ci:
        name: Linux
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - cc: gcc-9
                      cxx: g++-9
                      build_type: Release
                    - cc: gcc-9
                      cxx: g++-9
                      build_type: Debug

                    - cc: gcc-10
                      cxx: g++-10
                      build_type: Release
                    - cc: gcc-10
                      cxx: g++-10
                      build_type: Debug

                    - cc: clang-10
                      cxx: clang++-10
                      build_type: Release
                    - cc: clang-10
                      cxx: clang++-10
                      build_type: Debug

                    - cc: clang-11
                      cxx: clang++-11
                      build_type: Release
                    - cc: clang-11
                      cxx: clang++-11
                      build_type: Debug

                    - cc: clang-12
                      cxx: clang++-12
                      build_type: Release
                    - cc: clang-12
                      cxx: clang++-12
                      build_type: Debug
        env:
            CC: ${{matrix.cc}}
            CXX: ${{matrix.cxx}}
            PYTHON_EXECUTABLE: /usr/bin/python
            PYTHON3_EXECUTABLE: /usr/bin/python3
            INSTALL_PREFIX: /usr/local
        steps:
          - uses: actions/checkout@v2
          - name: Install dependencies
            run: |
                sudo apt install -y libpython2-dev libpython3-dev python-numpy python3-numpy doxygen luajit luarocks lua-ldoc
                sudo luarocks install luaunit
          - name: Build SoapySDR
            run: |
                mkdir -p ${{github.workspace}}/build
                cd ${{github.workspace}}/build
                cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DPYTHON_EXECUTABLE=${PYTHON_EXECUTABLE} -DPYTHON3_EXECUTABLE=${PYTHON3_EXECUTABLE} ${{github.workspace}}
                make
          - name: Install
            run: |
                cd ${{github.workspace}}/build
                sudo make install
                sudo ldconfig
          - name: Run unit tests
            run: |
                cd ${{github.workspace}}/build
                ctest --output-on-failure
          - name: Test SoapySDRUtil
            run: |
                SoapySDRUtil --info
                SoapySDRUtil --check=null
                SoapySDRUtil --make="driver=null"
          - name: Test Python bindings
            run: |
                export PYTHONPATH=$(${PYTHON_EXECUTABLE} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib(plat_specific=True, prefix='${INSTALL_PREFIX}'))")
                echo ${PYTHONPATH}
                ${PYTHON_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.getAPIVersion())"
                ${PYTHON_EXECUTABLE} -c "from SoapySDR import *; print(SOAPY_SDR_ABI_VERSION)"
                ${PYTHON_EXECUTABLE} -c "from SoapySDR import *; print(SOAPY_SDR_TIMEOUT)"
                ${PYTHON_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.errToStr(SoapySDR.SOAPY_SDR_TIMEOUT))"
                ${PYTHON_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.Device.make('driver=null'))"
          - name: Test Python3 bindings
            run: |
                export PYTHONPATH=$(${PYTHON3_EXECUTABLE} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib(plat_specific=True, prefix='${INSTALL_PREFIX}'))")
                echo ${PYTHONPATH}
                ${PYTHON3_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.getAPIVersion())"
                ${PYTHON3_EXECUTABLE} -c "from SoapySDR import *; print(SOAPY_SDR_ABI_VERSION)"
                ${PYTHON3_EXECUTABLE} -c "from SoapySDR import *; print(SOAPY_SDR_TIMEOUT)"
                ${PYTHON3_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.errToStr(SoapySDR.SOAPY_SDR_TIMEOUT))"
                ${PYTHON3_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.Device.make('driver=null'))"
          - name: Test LuaJIT bindings
            run: |
                luajit -e 'SoapySDR = require("SoapySDR"); print(SoapySDR.API_VERSION)'
                luajit -e 'SoapySDR = require("SoapySDR"); print(SoapySDR.ABI_VERSION)'
                luajit -e 'SoapySDR = require("SoapySDR"); print(SoapySDR.Error.TIMEOUT)'
                luajit -e 'SoapySDR = require("SoapySDR"); print(SoapySDR.Error.ToString(SoapySDR.Error.TIMEOUT))'
                luajit -e 'SoapySDR = require("SoapySDR"); print(SoapySDR.Device("driver=null"))'
    osx-ci:
        name: OS X
        runs-on: macos-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - cc: clang
                      cxx: clang++
                      build_type: Release
                    - cc: clang
                      cxx: clang++
                      build_type: Debug
        env:
            CC: ${{matrix.cc}}
            CXX: ${{matrix.cxx}}
            PYTHON_EXECUTABLE: /usr/bin/python
            PYTHON3_EXECUTABLE: /usr/bin/python3
            INSTALL_PREFIX: /usr/local
        steps:
          - uses: actions/checkout@v2
          - name: Install dependencies
            run: |
                brew install doxygen luajit
                which luajit
                pip install numpy
                pip3 install numpy

                # Installing Lua 5.1 dependencies via package is ugly
                cd ${{runner.workspace}}
                git clone https://github.com/bluebird75/luaunit.git -b LUAUNIT_V3_4
                sudo mkdir -p /usr/local/share/lua/5.1
                sudo cp luaunit/luaunit.lua /usr/local/share/lua/5.1
          - name: Build SoapySDR
            run: |
                mkdir -p ${{github.workspace}}/build
                cd ${{github.workspace}}/build
                cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DPYTHON_EXECUTABLE=${PYTHON_EXECUTABLE} -DPYTHON3_EXECUTABLE=${PYTHON3_EXECUTABLE} ${{github.workspace}}
                make
          - name: Install
            run: |
                cd ${{github.workspace}}/build
                sudo make install
          - name: Run unit tests
            run: |
                cd ${{github.workspace}}/build
                ctest --output-on-failure
          - name: Test SoapySDRUtil
            run: |
                SoapySDRUtil --info
                SoapySDRUtil --check=null
                SoapySDRUtil --make="driver=null"
          - name: Test LuaJIT bindings
            run: |
                luajit -e 'SoapySDR = require("SoapySDR"); print(SoapySDR.API_VERSION)'
                luajit -e 'SoapySDR = require("SoapySDR"); print(SoapySDR.ABI_VERSION)'
                luajit -e 'SoapySDR = require("SoapySDR"); print(SoapySDR.Error.TIMEOUT)'
                luajit -e 'SoapySDR = require("SoapySDR"); print(SoapySDR.Error.ToString(SoapySDR.Error.TIMEOUT))'
                luajit -e 'SoapySDR = require("SoapySDR"); print(SoapySDR.Device("driver=null"))'
    windows-ci:
        name: Windows
        runs-on: windows-latest
        strategy:
            fail-fast: false
            matrix:
                # Note: keeping cmake_config general enough for non-MSVC later
                include:
                    - cmake_config: -G "Visual Studio 14 2015" -A "Win32"
                      arch: win32
                      build_type: Release
                    - cmake_config: -G "Visual Studio 14 2015" -A "Win32"
                      arch: win32
                      build_type: Debug

                    - cmake_config: -G "Visual Studio 14 2015" -A "x64"
                      arch: x64
                      build_type: Release
                    - cmake_config: -G "Visual Studio 14 2015" -A "x64"
                      arch: x64
                      build_type: Debug

                      # Note: skipping VS2017, possible bugginess in parallel installs

                    - cmake_config: -G "Visual Studio 16 2019" -A "Win32"
                      arch: win32
                      build_type: Release
                    - cmake_config: -G "Visual Studio 16 2019" -A "Win32"
                      arch: win32
                      build_type: Debug

                    - cmake_config: -G "Visual Studio 16 2019" -A "x64"
                      arch: x64
                      build_type: Release
                    - cmake_config: -G "Visual Studio 16 2019" -A "x64"
                      arch: x64
                      build_type: Debug
        env:
            # Easier to have multiple copies of a subpath than deal with CI path parsing issues
            INSTALL_PREFIX: 'C:\Program Files\SoapySDR'
            LUAJIT_INSTALL_PREFIX: 'C:\Program Files\LuaJIT'
            LUAJIT_SHARE_LUA_51: 'C:\Program Files\LuaJIT\share\lua\5.1'
            LUA_PATH: 'C:\Program Files\LuaJIT\share\lua\5.1\?.lua;C:\Program Files\SoapySDR\share\lua\5.1\?\?.lua'
        steps:
          - uses: actions/checkout@v2
          - uses: ilammy/msvc-dev-cmd@v1
            with:
                arch: ${{matrix.arch}}
          - name: Install dependencies
            run: |
                mkdir -p "$Env:LUAJIT_SHARE_LUA_51"

                cd ${{runner.workspace}}
                git clone https://github.com/LuaJIT/LuaJIT.git -b v2.1
                cd LuaJIT\src
                .\msvcbuild.bat
                cp luajit.exe "$Env:LUAJIT_INSTALL_PREFIX"
                cp lua51.dll "$Env:LUAJIT_INSTALL_PREFIX"
                cp -r jit "$Env:LUAJIT_INSTALL_PREFIX"

                cd ${{runner.workspace}}
                git clone https://github.com/bluebird75/luaunit.git -b LUAUNIT_V3_4
                cp -v luaunit\luaunit.lua "$Env:LUAJIT_SHARE_LUA_51"
          - name: Build SoapySDR
            run: |
                $Env:PATH += ";$Env:LUAJIT_INSTALL_PREFIX"
                mkdir ${{github.workspace}}\build
                cd ${{github.workspace}}\build
                cmake ${{matrix.cmake_config}} -DENABLE_PYTHON=OFF -DCMAKE_INSTALL_PREFIX="$Env:INSTALL_PREFIX" -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ${{github.workspace}}
                cmake --build . --config ${{matrix.build_type}}
          - name: Install
            run: |
                cd ${{github.workspace}}\build
                cmake --install . --config ${{matrix.build_type}}
          - name: Run unit tests
            run: |
                $Env:PATH += ";$Env:INSTALL_PREFIX\bin;$Env:LUAJIT_INSTALL_PREFIX"
                cd ${{github.workspace}}\build
                ctest --output-on-failure -C ${{matrix.build_type}}
          - name: Test SoapySDRUtil
            run: |
                $Env:PATH += ";$Env:INSTALL_PREFIX\bin"
                SoapySDRUtil --info
                SoapySDRUtil --check=null
                SoapySDRUtil --make="driver=null"
          - name: Test LuaJIT bindings
            run: |
                $Env:PATH += ";$Env:INSTALL_PREFIX\bin;$Env:LUAJIT_INSTALL_PREFIX"
                luajit -e "SoapySDR = require('SoapySDR'); print(SoapySDR.API_VERSION)"
                luajit -e "SoapySDR = require('SoapySDR'); print(SoapySDR.ABI_VERSION)"
                luajit -e "SoapySDR = require('SoapySDR'); print(SoapySDR.Error.TIMEOUT)"
                luajit -e "SoapySDR = require('SoapySDR'); print(SoapySDR.Error.ToString(SoapySDR.Error.TIMEOUT))"
                luajit -e "SoapySDR = require('SoapySDR'); print(SoapySDR.Device('driver=null'))"
